# Generated by Django 4.2.1 on 2023-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='zone_description',
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_name',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
