# Generated by Django 4.2.1 on 2023-12-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0004_remove_level_leve_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='mode_status',
        ),
    ]
