# Generated by Django 4.2.1 on 2023-12-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cour_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cour_description', models.TextField(blank=True, null=True)),
                ('cour_material', models.TextField(blank=True, null=True)),
                ('alterno', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('leve_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('leve_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memb_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('memb_dni', models.TextField()),
                ('memb_typedni', models.CharField(blank=True, max_length=3, null=True)),
                ('memb_name', models.TextField()),
                ('memb_surname', models.TextField()),
                ('memb_mobil', models.TextField()),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('mode_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('mode_description', models.TextField(blank=True, null=True)),
                ('mode_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('peri_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('peri_description', models.TextField(blank=True, null=True)),
                ('peri_start', models.DateField(blank=True, null=True)),
                ('peri_end', models.DateField(blank=True, null=True)),
                ('peri_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sche_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sche_description', models.TextField(blank=True, null=True)),
                ('sche_day', models.SmallIntegerField(blank=True, null=True)),
                ('sche_starttime', models.TimeField(blank=True, null=True)),
                ('sche_endtime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('seas_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('seas_status', models.BooleanField(blank=True, null=True)),
                ('seas_glosa', models.TextField()),
                ('seas_course', models.ForeignKey(blank=True, db_column='seas_course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.course')),
                ('seas_mode', models.ForeignKey(blank=True, db_column='seas_mode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.mode')),
                ('seas_period', models.ForeignKey(blank=True, db_column='seas_period', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.period')),
                ('seas_schedule', models.ForeignKey(blank=True, db_column='seas_schedule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.schedule')),
                ('seas_teacher', models.ForeignKey(blank=True, db_column='seas_teacher', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.member')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('zone_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('seas_final', models.SmallIntegerField(blank=True, null=True)),
                ('seas_ses01', models.BooleanField(blank=True, null=True)),
                ('seas_ses02', models.BooleanField(blank=True, null=True)),
                ('seas_ses03', models.BooleanField(blank=True, null=True)),
                ('seas_ses04', models.BooleanField(blank=True, null=True)),
                ('seas_ses05', models.BooleanField(blank=True, null=True)),
                ('seas_ses06', models.BooleanField(blank=True, null=True)),
                ('seas_ses07', models.BooleanField(blank=True, null=True)),
                ('seas_ses08', models.BooleanField(blank=True, null=True)),
                ('seas_ses09', models.BooleanField(blank=True, null=True)),
                ('seas_ses10', models.BooleanField(blank=True, null=True)),
                ('seas_ses11', models.BooleanField(blank=True, null=True)),
                ('seas_ses12', models.BooleanField(blank=True, null=True)),
                ('stud_member', models.ForeignKey(blank=True, db_column='stud_member', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.member')),
                ('stud_season', models.ForeignKey(blank=True, db_column='stud_season', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.season')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='memb_zone',
            field=models.ForeignKey(blank=True, db_column='memb_zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.zone'),
        ),
        migrations.AddField(
            model_name='course',
            name='cour_level',
            field=models.ForeignKey(blank=True, db_column='cour_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.level'),
        ),
    ]
