# Generated by Django 4.2.1 on 2023-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0003_alter_zone_zone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='leve_description',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='mode_description',
        ),
        migrations.AddField(
            model_name='level',
            name='leve_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mode',
            name='mode_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
