# Generated by Django 3.2.21 on 2023-12-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0005_remove_mode_mode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_member',
            field=models.ForeignKey(db_column='stud_member', on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.member'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_season',
            field=models.ForeignKey(db_column='stud_season', on_delete=django.db.models.deletion.DO_NOTHING, to='eseme.season'),
        ),
    ]
